# Generated by Django 3.2.16 on 2023-01-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Result'},
        ),
        migrations.AlterField(
            model_name='results',
            name='eps',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
