# Generated by Django 3.2.16 on 2023-01-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_auto_20230104_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='depreciation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='net_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='opm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='other_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='profit_before_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
