# Generated by Django 3.2.16 on 2023-01-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_auto_20230104_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='operating_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
