# Generated by Django 3.2.16 on 2023-01-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0004_auto_20230104_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'ordering': ('date',), 'verbose_name': 'Result'},
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Q', 'Quarterly'), ('A', 'Annually')], default='A', max_length=20)),
                ('share_capital', models.IntegerField(blank=True, null=True)),
                ('reserves', models.IntegerField(blank=True, null=True)),
                ('borrowings', models.IntegerField(blank=True, null=True)),
                ('other_liabilities', models.IntegerField(blank=True, null=True)),
                ('total_liabilities', models.IntegerField(blank=True, null=True)),
                ('fixed_assets', models.IntegerField(blank=True, null=True)),
                ('cwip', models.IntegerField(blank=True, null=True)),
                ('investments', models.IntegerField(blank=True, null=True)),
                ('other_assets', models.IntegerField(blank=True, null=True)),
                ('total_assets', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupees'), ('USD', 'American Dollar')], default='INR', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.company')),
            ],
            options={
                'verbose_name': 'Balance Sheet',
                'ordering': ('date',),
            },
        ),
    ]
