# Generated by Django 3.2.16 on 2023-01-06 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0005_auto_20230106_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Q', 'Quarterly'), ('A', 'Annually')], default='Q', max_length=20)),
                ('promoters_pct', models.FloatField(blank=True, null=True)),
                ('fii_pct', models.FloatField(blank=True, null=True)),
                ('dii_pct', models.FloatField(blank=True, null=True)),
                ('government_pct', models.FloatField(blank=True, null=True)),
                ('public_pct', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.company')),
            ],
            options={
                'verbose_name': 'Shareholding',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Q', 'Quarterly'), ('A', 'Annually')], default='A', max_length=20)),
                ('debtor_days', models.IntegerField(blank=True, null=True)),
                ('inventory_days', models.IntegerField(blank=True, null=True)),
                ('days_payable', models.IntegerField(blank=True, null=True)),
                ('cash_conversion_cycle', models.IntegerField(blank=True, null=True)),
                ('working_capital_days', models.IntegerField(blank=True, null=True)),
                ('roce_pct', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.company')),
            ],
            options={
                'verbose_name': 'Ratios',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Q', 'Quarterly'), ('A', 'Annually')], default='A', max_length=20)),
                ('operating', models.IntegerField(blank=True, null=True)),
                ('investing', models.IntegerField(blank=True, null=True)),
                ('financing', models.IntegerField(blank=True, null=True)),
                ('net', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupees'), ('USD', 'American Dollar')], default='INR', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.company')),
            ],
            options={
                'verbose_name': 'Cash Flow',
                'ordering': ('date',),
            },
        ),
    ]
