# Generated by Django 3.2.16 on 2022-10-23 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20221017_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=512)),
                ('tweet_created_at', models.DateField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.twitteraccount')),
            ],
        ),
    ]
