# Generated by Django 3.2.16 on 2022-10-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='acct_id',
            new_name='tweeter_account',
        ),
    ]
