# Generated by Django 3.2.16 on 2022-10-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_acct_id_tweets_tweeter_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='tweeter_account',
            new_name='twitter_account',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet_created_at',
            field=models.DateTimeField(),
        ),
    ]
