# Generated by Django 3.2.16 on 2022-10-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20221023_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name': 'Tweets'},
        ),
        migrations.AddField(
            model_name='tweets',
            name='tweet_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
