# Generated by Django 3.2.16 on 2022-10-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20221024_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256, unique=True)),
                ('accept', models.BooleanField(default=False)),
            ],
        ),
    ]
