# Generated by Django 3.2.16 on 2022-10-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_filterkeywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterkeywords',
            options={'verbose_name': 'Tweet Filters'},
        ),
        migrations.AlterModelOptions(
            name='usertweet',
            options={'verbose_name': 'User Tweet'},
        ),
        migrations.AddField(
            model_name='filterkeywords',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
