# Generated by Django 3.2.16 on 2022-10-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20221029_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='accept',
            field=models.BooleanField(null=True),
        ),
    ]
