# Generated by Django 3.2.16 on 2022-10-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_tweets_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='filter_reason',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='accept',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
